name: CI

# 1️⃣ Trigger on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    # 2️⃣ Run on the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # 3️⃣ Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 4️⃣ Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 5️⃣ Install dependencies (including Flake8)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn requests python-dotenv openai flake8 pytest

      # 6️⃣ Lint your code with Flake8
      - name: Lint with Flake8
        run: |
          flake8 .

      # 7️⃣ (Optional) Run your test suite
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
